plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.studybolt.ondeviceai'
version = '1.0.0'

android {
  namespace 'com.studybolt.ondeviceai'

  defaultConfig {
    minSdkVersion 26
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.google.mlkit:genai-prompt:1.0.0-beta4'
}
